name: unit-tests
on: [push]

jobs:
  build:
    name: unit-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: install tools
        run: |
             sudo apt install cmake
             sudo apt install lcov
          
      - name: build test runner
        run: |
             cd ..
             git clone https://github.com/catchorg/Catch2.git
             cd tinyexpr-plusplus/tests
             cmake ./
             make

      - name: run tests
        run: |
             TETestRunner --reporter JUnit::out=TE-junit.xml
 
      - name: review results
        run: |
             cat TE-junit.xml
             
