name: unit-tests
on: [push]

jobs:
  build:
    name: unit-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: install tools
        run: |
             sudo apt install cmake
             sudo apt install lcov
          
      - name: build & run tests
        run: |
             cd ..
             git clone https://github.com/catchorg/Catch2.git
             cd tinyexpr-plusplus/tests
             cmake ./
             make
             cd bin
             ./TETestRunner --reporter JUnit::out=TE-junit.xml
             cat TE-junit.xml
             errors=$(cat TE-junit.xml | grep -Po '(errors)="\K[^"]*')
             failures=$(cat TE-junit.xml | grep -Po '(failures)="\K[^"]*')
             echo "var value is: ${errors}"
             echo "var value is: ${failures}"
             if ([ "$errors" -gt "0" ];)
               exit 1
             fi
             if ([ "$failures" -gt "0" ];)
               exit 1
             fi

      - uses: actions/upload-artifact@v3
        with:
          name: test runner results
          path: TE-junit.xml

             
