name: unit-tests
on: [push]

jobs:
  build:
    name: unit-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: install tools
        run: |
             sudo apt install cmake
             sudo apt install lcov
          
      - name: build & run tests
        run: |
             cd ..
             git clone https://github.com/catchorg/Catch2.git
             cd tinyexpr-plusplus/tests
             cmake ./
             make
             ls
             cd bin
             ls
             TETestRunner --reporter JUnit::out=TE-junit.xml
             ls
             cat TE-junit.xml
             
